/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "FreeRTOS.h"
#include "task.h"
#include <stm32f4xx.h>

#include <stdint.h>
#include <stdio.h>
#include "GPIOxDriver.h"
#include "PLLDriver.h"


#define STACK_SIZE 200

/* Función que inicializa el USART2 para el Segger */
extern void SEGGER_UART_init(uint32_t);

/* Definición de variables del sistema */
uint32_t SystemCoreClock = 16000000;

/* Prototipos de funciones */
void vTaskOne( void * pvParameters );
void vTaskTwo( void * pvParameters );

GPIO_Handler_t handlerBlinkyPin = {0}; // LED de estado del Pin A5

int main(void)
{

	/* Activamos la unidad de punto flotante (FPU) */
	SCB->CPACR    |= (0xF << 20);

	/* Activamos del contador de Ticks */
	DWT->CTRL    |= (1 << 0);

	configPLL(100);

	/* GPIO del Blinky Led de Estado PA5 */
	handlerBlinkyPin.pGPIOx								= GPIOA;
	handlerBlinkyPin.GPIO_PinConfig.GPIO_PinNumber 		= PIN_5;
	handlerBlinkyPin.GPIO_PinConfig.GPIO_PinMode		= GPIO_MODE_OUT;
	handlerBlinkyPin.GPIO_PinConfig.GPIO_PinSpeed 		= GPIO_OSPEED_FAST;
	handlerBlinkyPin.GPIO_PinConfig.GPIO_PinOPType 		= GPIO_OTYPE_PUSHPULL;
	// Cargo la configuración
	GPIO_Config(&handlerBlinkyPin);
	// Comienzo en estado bajo
	GPIO_WritePin(&handlerBlinkyPin, SET);

	float var = 5.5f/25.3f;
	(void)var;


    /* Loop forever */
	while(1){
		/* Si llegamos acá, es que algo falla */

	}
}

